/*
 * generated by Xtext
 */
package it.marcotinacci.turingmachine.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import it.marcotinacci.turingmachine.ui.internal.TuringMachineActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TuringMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TuringMachineActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TuringMachineActivator.getInstance().getInjector(TuringMachineActivator.IT_MARCOTINACCI_TURINGMACHINE_TURINGMACHINE);
	}
	
}
