/*
 * generated by Xtext
 */
package it.marcotinacci.xturing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XTuringUiModule extends it.marcotinacci.xturing.ui.AbstractXTuringUiModule {
	public XTuringUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
