/*
 * generated by Xtext
 */
package it.marcotinacci.turingmachine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TuringMachineUiModule extends it.marcotinacci.turingmachine.ui.AbstractTuringMachineUiModule {
	public TuringMachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
