/*
* generated by Xtext
*/
package it.marcotinacci.xturing;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XTuringUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.marcotinacci.xturing.ui.internal.XTuringActivator.getInstance().getInjector("it.marcotinacci.xturing.XTuring");
	}
	
}
