/*
* generated by Xtext
*/
package it.marcotinacci.turingmachine.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TuringMachineOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
