/*
* generated by Xtext
*/
package it.marcotinacci.xturing.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.marcotinacci.xturing.services.XTuringGrammarAccess;

public class XTuringParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XTuringGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.marcotinacci.xturing.parser.antlr.internal.InternalXTuringParser createParser(XtextTokenStream stream) {
		return new it.marcotinacci.xturing.parser.antlr.internal.InternalXTuringParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Machine";
	}
	
	public XTuringGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XTuringGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
