/*
* generated by Xtext
*/
package it.marcotinacci.turingmachine.ui.contentassist;

import it.marcotinacci.turingmachine.ui.contentassist.AbstractTuringMachineProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TuringMachineProposalProvider extends AbstractTuringMachineProposalProvider {

}
