/*
 * generated by Xtext
 */
package it.marcotinacci.xturing.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import it.marcotinacci.xturing.ui.internal.XTuringActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XTuringExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XTuringActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XTuringActivator.getInstance().getInjector(XTuringActivator.IT_MARCOTINACCI_XTURING_XTURING);
	}
	
}
