/*
* generated by Xtext
*/
package it.marcotinacci.turingmachine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TuringMachineUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.marcotinacci.turingmachine.ui.internal.TuringMachineActivator.getInstance().getInjector("it.marcotinacci.turingmachine.TuringMachine");
	}
	
}
