/*
* generated by Xtext
*/
package it.marcotinacci.xturing.ui.contentassist;

import it.marcotinacci.xturing.ui.contentassist.AbstractXTuringProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XTuringProposalProvider extends AbstractXTuringProposalProvider {

}
