/*
* generated by Xtext
*/
package it.marcotinacci.turingmachine.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.marcotinacci.turingmachine.services.TuringMachineGrammarAccess;

public class TuringMachineParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TuringMachineGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.marcotinacci.turingmachine.parser.antlr.internal.InternalTuringMachineParser createParser(XtextTokenStream stream) {
		return new it.marcotinacci.turingmachine.parser.antlr.internal.InternalTuringMachineParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Machine";
	}
	
	public TuringMachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TuringMachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
