/*
 * generated by Xtext
 */
package it.marcotinacci.xturing;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XTuringRuntimeModule extends it.marcotinacci.xturing.AbstractXTuringRuntimeModule {

}
