/*
 * generated by Xtext
 */
package it.marcotinacci.turingmachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TuringMachineRuntimeModule extends it.marcotinacci.turingmachine.AbstractTuringMachineRuntimeModule {

}
